    <div id="main-content">
		     <div id="banner">
				<h1><a href="#">Izwebz.com></a></h1>
				<div id="playnow">
					<input class="button" type="submit" value="Play now">
				</div>				
				<div id="platforms">
					<select class="select" name="platforms">
						<option value=0>platforms </option>
						<option value=1>Android</option>
						<option value=2>iPhone</option>							
					</select>
				</div>
				<div id="social-platforms">
					<select class="select" name="platforms">
						<option value=0>social platforms </option>
						<option value=1>Facebook</option>
						<option value=2>yahoo</option>							
					</select>
				</div>
			</div><!--End #banner-->
			<div id="listbox">
				<div id="news">
						<h2><a href="#">News</a></h2>
						<h4><a href="#">Maria Osawa</a></h4>
						<h4><a href="#">Maria Osawa</a></h4>
						<h4><a href="#">Osama Biladen</a></h4>
						<h4><a href="#">Osama Biladen</a></h4>
				</div><!-- End #news -->
							
				<div id="charge">
						<h2><a href="#">Charge</a></h2>
						<h4><a href="#">- SMS</a></h4>
						<h4><a href="#">- ATM</a></h4>
						<h4><a href="#">- Paypal</a></h4>
						<h4><a href="#">- Thẻ cào</a></h4>
						<h4><a href="#">....</a></h4>
				</div><!-- End #charge -->
				
				<div id="sport">
						<h2><a href="#">Sport</a></h2>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consequat iaculis sapien eget volutpat. Maecenas blandit pellentesque lorem vitae condimentum. Integer aliquam, est ut auctor molestie, nunc orci euismod magna, eu condimentum mi lorem at velit. Nulla non leo et tortor mattis dignissim. 
						</p>
				</div><!--End #sport   --> 
			</div><!-- End listbox -->
			<div id="listboxgame">	
				 <form method="get" id="" action=" ">			 
				 	<input id="vegas" type="submit" value="">	
				 	
				 </form>			
				 <p>Vegas game</p>
			</div><!-- End listboxgame -->
			<script>
			$(function() {
				$( "#datepicker" ).datepicker();
				$( "#anim" ).change(function() {
					$( "#datepicker" ).datepicker( "option", "showAnim", $( this ).val() );
				});
			});
			</script>		
			<div class="demo">
				<h5>Date: <input type="text" id="datepicker" size="30"/></h5>
			</div><!-- End demo -->
		</div><!--End #content-->
