<div id="main-content">
	<div id="left-social">
		<div id="info-user">
			<div id="avata">
				<img src="<?php echo $this->imgUrl  ?>/bt2.jpg" alt="" />
			</div><!--   End avata--> 
			<div id="money">
			<h2>$3000</h2>
			</div>
			<div id="aaaaa">
				<a href="#"> Info </a>
			</div>
			<div id="aaaaa">
				<a href="#"> Budies </a>
			</div>
		</div>   <!--   End info-user-->
		<div id="lst-friends">
		 	<div id="aaaaa">
				<a href="#"> Budies(222) </a>
			</div>
			<div id="item-friends">
				 <form method="get" id="" action=" ">			 
				 	<input id="avata-small" type="submit" value="">				 	
				 </form>
				<h3> Full name </h3>
				<br><h3> Sở thích </h3>
			</div> <!--   End item-friends-->
			<div id="item-friends">
				 <form method="get" id="" action=" ">			 
				 	<input id="avata-small" type="submit" value="">				 	
				 </form>
				<h3> Full name </h3>
				<br><h3> Sở thích </h3>
			</div><!--   End item-friends-->
			<div id="item-friends">
				<form method="get" id="" action=" ">			 
				 	<input id="avata-small" type="submit" value="">				 	
				 </form>
				<h3> Full name </h3>
				<br><h3> Sở thích </h3>
			</div><!--   End item-friends-->
		</div>  <!--   End lst-friend-->   
	</div><!--  End left-social --> 
	<div id="primary">
		<div id="class">
			<h1>Class</h1>
			<a> Vip </a>
			<br><a> Level </a>
			<br><a> Money </a>
		</div><!--   End class-->
		<div id="basic">
			<h1>Basic</h1>	
			<div id="playnow">
				<form method="get" id="" action=" ">			 
					 	<input class="button" type="submit" value="Edit">			 	
				 </form>		
			</div>
			<a> UserName  : </a>
			<br><a> Fullname  : </a>
			<br><a> Email  : </a>
			<br><a> Gender  : </a>
			<br><a> Birthday  : </a>
			<br><a> Country  : </a>
		</div><!--   End class-->
	</div><!--   Endprimary-->
</div><!-- End main-content -->
