
<script>
	$(function() {
		// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
		
		var name = $( "#name" ),
			email = $( "#email" ),
			password = $( "#password" ),
			allFields = $( [] ).add( name ).add( email ).add( password ),
			tips = $( ".validateTips" );

		function updateTips( t ) {
			tips
				.text( t )
				.addClass( "ui-state-highlight" );
			setTimeout(function() {
				tips.removeClass( "ui-state-highlight", 1500 );
			}, 500 );
		}

		function checkLength( o, n, min, max ) {
			if ( o.val().length > max || o.val().length < min ) {
				o.addClass( "ui-state-error" );
				updateTips( "Length of " + n + " must be between " +
					min + " and " + max + "." );
				return false;
			} else {
				return true;
			}
		}

		function checkRegexp( o, regexp, n ) {
			if ( !( regexp.test( o.val() ) ) ) {
				o.addClass( "ui-state-error" );
				updateTips( n );
				return false;
			} else {
				return true;
			}
		}
		
		$( "#dialog-form" ).dialog({
			autoOpen: false,
			height: 300,
			width: 350,
			modal: true,
			buttons: {
				"Create an account": function() {
					var bValid = true;
					allFields.removeClass( "ui-state-error" );

					bValid = bValid && checkLength( name, "username", 3, 16 );
					bValid = bValid && checkLength( email, "email", 6, 80 );
					bValid = bValid && checkLength( password, "password", 5, 16 );

					bValid = bValid && checkRegexp( name, /^[a-z]([0-9a-z_])+$/i, "Username may consist of a-z, 0-9, underscores, begin with a letter." );
					// From jquery.validate.js (by joern), contributed by Scott Gonzalez: http://projects.scottsplayground.com/email_address_validation/
					bValid = bValid && checkRegexp( email, /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i, "eg. ui@jquery.com" );
					bValid = bValid && checkRegexp( password, /^([0-9a-zA-Z])+$/, "Password field only allow : a-z 0-9" );

					if ( bValid ) {
						$( "#users tbody" ).append( "<tr>" +
							"<td>" + name.val() + "</td>" + 
							"<td>" + email.val() + "</td>" + 
							"<td>" + password.val() + "</td>" +
						"</tr>" ); 
						$( this ).dialog( "close" );
					}
				},
				Cancel: function() {
					$( this ).dialog( "close" );
				}
			},
			close: function() {
				allFields.val( "" ).removeClass( "ui-state-error" );
			}
		});

		$( "#create-user" )
			.button()
			.click(function() {
				$( "#dialog-form" ).dialog( "open" );
			});
	});
	</script>
<div id="main-content">
	<div id="left-social">
		<div id="info-user">
			<div id="avata">
				<img src="<?php echo $this->imgUrl  ?>/bt2.jpg" alt="" />
			</div><!--   End avata--> 
			<div id="money">
			<h2>$3000</h2>
			</div>
			<div id="aaaaa">
				<a href="#"> Info </a>
			</div>
			<div id="aaaaa">
				<a href="#"> Budies </a>
			</div>
		</div>   <!--   End info-user-->
		<div id="lst-friends">
		 	<div id="aaaaa">
				<a href="#"> Budies(222) </a>
			</div>
			<div id="item-friends">
				 <form method="get" id="" action=" ">			 
				 	<input id="avata-small" type="submit" value="">				 	
				 </form>
				<h3> Full name </h3>
				<br><h3> Sở thích </h3>
			</div> <!--   End item-friends-->
			<div id="item-friends">
				 <form method="get" id="" action=" ">			 
				 	<input id="avata-small" type="submit" value="">				 	
				 </form>
				<h3> Full name </h3>
				<br><h3> Sở thích </h3>
			</div><!--   End item-friends-->
			<div id="item-friends">
				<form method="get" id="" action=" ">			 
				 	<input id="avata-small" type="submit" value="">				 	
				 </form>
				<h3> Full name </h3>
				<br><h3> Sở thích </h3>
			</div><!--   End item-friends-->
		</div>  <!--   End lst-friend-->   
	</div><!--  End left-social --> 
	<div id="primary">
		<div id="class">
			<h1>Class</h1>
			<a> Vip </a>
			<br><a> Level </a>
			<br><a> Money </a>
		</div><!--   End class-->
		<div id="basic">
			<h1>Basic</h1>	
			<div id="playnow">
				<form method="get" id="create-user" action=" ">			 
					 	<input class="button" type="button" value="Edit">			 	
				 </form>		
			</div>
			<a> UserName  : </a>
			<br><a> Fullname  : </a>
			<br><a> Email  : </a>
			<br><a> Gender  : </a>
			<br><a> Birthday  : </a>
			<br><a> Country  : </a>
		</div><!--   End class-->
	</div><!--   Endprimary-->
	<div id="dialog-form" title="Create new user">
	<p class="validateTips">All form fields are required.</p>

	<form>
	<fieldset >
		<p> Name</p>
		<input type="text" name="" id="datepicker" class=""  style="width:200px" />
		<br><p for="email">Email</p>
		<input type="text" name="email" id="email" value="" class="text ui-widget-content ui-corner-all" />
		<br><p for="password">Password</p>
		<input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all" />
	</fieldset>
	</form>
</div>
</div><!-- End main-content -->
